import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'
import styles from './page.module.scss'
import { Provider } from './provider'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Management',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang='en'>
        <body className={inter.className}>
        <Provider>
            <header className={styles.header}>
                <Link className={styles.link} href={'/'}>
                    Home
                </Link>
                <Link className={styles.link} href={'/auth'}>
                    Auth
                </Link>
                {/*<Link className={styles.link} href={'/profile'}>*/}
                {/*    Profile*/}
                {/*</Link>*/}
                <Link className={styles.link} href={'/admin'}>
                    Admin
                </Link>
            </header>
            {children}
        </Provider>
        </body>
        </html>
    )
}